name: Strapi CI/CD - Docker & Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO_NAME: strapi-repo

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4️⃣ Build & Push Docker image
      - name: Build & Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          echo "IMAGE_TAG=$IMAGE_TAG"
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID"

          # Ensure ECR repo exists
          aws ecr describe-repositories --repository-names $ECR_REPO_NAME || \
          aws ecr create-repository --repository-name $ECR_REPO_NAME

          # Build Docker image from strapi-app/
          docker build -t $ECR_REPO_NAME:$IMAGE_TAG ./strapi-app

          # Tag and push
          docker tag $ECR_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG

          # Save image URI for Terraform
          echo "ECR_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      # 5️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

     terraform apply -auto-approve \
      -var "db_username=${DB_USERNAME}" \
      -var "db_password=${DB_PASSWORD}" \
      -var "db_name=${DB_NAME}" \
      -var "app_keys=${APP_KEYS}" \
      -var "api_token_salt=${API_TOKEN_SALT}" \
      -var "admin_jwt_secret=${ADMIN_JWT_SECRET}" \
      -var "jwt_secret=${JWT_SECRET}" \
      -var "execution_role_arn=${EXECUTION_ROLE_ARN}" \
      -var "task_role_arn=${TASK_ROLE_ARN}" \
      -var "ecr_url=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/strapi-repo:4387ccac"
      # 7️⃣ Output ECS service & ALB DNS
      - name: Show ALB DNS
        run: |
          cd terraform
          terraform output alb_dns
